psf: BoxPeakShape Class Reference
BoxPeakShape Class Reference
Public Member Functions
BoxPeakShape (const double sigma=0.1, const double sigmaFactorForSupportThreshold=3.0)
double at (const double xCoordinate) const
double getFwhm () const
double getSigma () const
double getSigmaFactorForSupportThreshold () const
double getSupportThreshold () const
void setFwhm (const double fwhm)
void setSigma (const double sigma)
void setSigmaFactorForSupportThreshold (const double factor)
Protected Member Functions
double sigmaToFwhmConversionFactor () const
Private Attributes
double sigma_
double sigmaFactorForSupportThreshold_
Friends
struct ::peakshapeTestSuite
Detailed Description
A Gaussian-based box peak shape.
The idea is that centroided data can more efficiently and probably also more accurately be fit using a box peak shape. This is because the integration over the true signal PSF is carried out by the instrument, and depending on the vendor's propietray centroiding algorithms, the true m_0 may shift slightly back and forth. In this case, as the PSF intensities have already been integrated into the centroid intensity, it is not suitable to weight the observation by its devaition from the expected zero: we either take all or nothig. Nonetheless, the width of the function needs to be adapted properly and that is why we rely on the Gaussian that would be used for profile data.
See also:
psf::PeakShape
Author:
Bernhard Kausler <bernhard.kausler@iwr.uni-heidelberg.de>
Marc Kirchner <marc.kirchner@childrens.harvard.edu>
Date:
2009-10-02
Definition at line 98 of file PeakShape.h.
Member Function Documentation
double getFwhm () const
Gets the full width at half maximum.
Definition at line 36 of file BoxPeakShape.cpp.
References BoxPeakShape::sigmaToFwhmConversionFactor().
double getSigma () const
Gets the sigma parameter of the Gaussian the underlies the box.
Definition at line 126 of file PeakShape.h.
Referenced by BoxPeakShape::getSupportThreshold().
double getSigmaFactorForSupportThreshold () const
Returns the factor used in the support threshold calculation.
Definition at line 44 of file BoxPeakShape.cpp.
Referenced by BoxPeakShape::getSupportThreshold().
double getSupportThreshold () const
The support threshold for the box is calculated based on a Gaussian according to 'sigma x sigmaFactorForSupportThreshold'.
Definition at line 13 of file BoxPeakShape.cpp.
References BoxPeakShape::getSigma(), and BoxPeakShape::getSigmaFactorForSupportThreshold().
void setFwhm (const double fwhm)
Sets the full width at half maximum.
This changes the sigma parameter according to .
Parameters:
fwhm Has to be positive.
Exceptions:
psf::PreconditionViolation fwhm is not positive.
Definition at line 32 of file BoxPeakShape.cpp.
References BoxPeakShape::sigmaToFwhmConversionFactor().
void setSigma (const double sigma)
Sets the sigma parameter of the underlying Gaussian.
Parameters:
sigma Has to be positive.
Exceptions:
psf::PreconditionViolation Sigma is not positive.
Definition at line 26 of file BoxPeakShape.cpp.
void setSigmaFactorForSupportThreshold (const double factor)
Sets the factor for the threshold calculation.
Parameters:
factor Has to be positive.
Exceptions:
psf::PreconditionViolation factor is not positive.
Definition at line 40 of file BoxPeakShape.cpp.
double sigmaToFwhmConversionFactor () const [protected]
Definition at line 48 of file BoxPeakShape.cpp.
Referenced by BoxPeakShape::getFwhm(), and BoxPeakShape::setFwhm().
The documentation for this class was generated from the following files:
PeakShape.h
BoxPeakShape.cpp