psf: Log< T > Class Template Reference
Log< T > Class Template Reference
Public Member Functions
std::ostringstream & get (LogLevel level=logINFO)
Static Public Member Functions
static LogLevel fromString (const std::string &level)
static LogLevel & getReportingLevel ()
static std::string toString (LogLevel level)
Protected Attributes
std::ostringstream os_
Private Member Functions
Log (const Log &)
Log & operator= (const Log &)
Detailed Description
template<typename T>
class psf::Log< T >
A thread-safe logging tool
The Log<T> passes its internal logging stream to a Redirector T.
You have to provide a Redirector with the following interface:
 void T::output(const std::string& msg)
Author:
Bernhard X. Kausler <bernhard.kausler@iwr.uni-heidelberg.de>
Date:
2009-04-02
Definition at line 170 of file Log.h.
Member Function Documentation
psf::LogLevel fromString (const std::string & level) [static]
Converts from string to a enumerated logging level
For example: "INFO" to logINFO.
Definition at line 299 of file Log.h.
std::ostringstream & get (LogLevel level = logINFO)
The internal logging stream.
Calling this function writes something like the following into the internal logging stream (depending on the chosen logging level and the current time):
 '- 16:17:23.714 WARNING: '
Afterwards, it returns a reference to that internal stream.
Definition at line 243 of file Log.h.
References Log< T >::getReportingLevel(), psf::nowTime(), Log< T >::os_, and Log< T >::toString().
psf::LogLevel & getReportingLevel () [static]
Returns the deepest logging level available.
This function can be used as a safeguard in the logging macros to defend against illegal user defined global logging levels.
Returns:
The deepest psf::LogLevel available.
Definition at line 274 of file Log.h.
Referenced by Log< T >::get(), and Log< T >::toString().
std::string toString (LogLevel level) [static]
Converts enumerated logging level to a string.
For example: logINFO to "INFO".
Definition at line 284 of file Log.h.
References Log< T >::getReportingLevel().
Referenced by Log< T >::get().
Member Data Documentation
std::ostringstream os_ [protected]
Internal string stream used for logging messages.
In the destructor, this stream is written to the Redirector T.
Definition at line 223 of file Log.h.
Referenced by Log< T >::get().
The documentation for this class was generated from the following file:
Log.h