psf: ParameterModel Class Reference
ParameterModel Class Reference
Public Member Functions
virtual double getParameter (unsigned index)
virtual unsigned int numberOfParameters ()=0
virtual void setParameter (unsigned index, double value)=0
Protected Member Functions
virtual ~ParameterModel ()
virtual double at (double x) const =0
virtual GeneralizedSlope slopeInParameterSpaceFor (double x) const =0
Detailed Description
The interface for the peak parameter policy to be used in psf::PeakParameterFwhm.
Attention:
This interface exists only for the purpose of documentation. Don't inherit from it, but simply implement it.
See also:
psf::PeakParameterFwhm
Author:
Bernhard Kausler <bernhard.kausler@iwr.uni-heidelberg.de>
Definition at line 326 of file PeakParameter.h.
Constructor & Destructor Documentation
virtual ~ParameterModel () [protected, virtual]
Protected non-virtual destructor.
This is a so called 'policy class'. The host class is inheriting from it to add its functionality. But it is not intended to be used as a base class. In case the user utilizes the policy as a baseclass anyway, we have to prevent calling 'delete' on it (deleting a baseclass with a non-virtual destructor leads to undefined behaviour). So we declare the destructor 'protected'.
See also:
http://en.wikipedia.org/wiki/Policy_based_design
Definition at line 345 of file PeakParameter.h.
Member Function Documentation
virtual double at (double x) const [protected, pure virtual]
Value of the model at position x.
Implemented in PeakParameterFwhm< ParameterModel >.
Referenced by PeakParameterFwhm< ParameterModel >::at().
virtual double getParameter (unsigned index) [virtual]
0 <= index < this->numberOfParameters() .
Attention:
: Don't implement, if the model has no parameters. This will cause desirable compile time errors, if one tries to learn a model without parameters.
Exceptions:
psf::PreconditionViolation Parameter index is out of range or the number of parameters is zero.
virtual unsigned int numberOfParameters () [pure virtual]
The number of parameters in the model.
May be any positive number including zero. This is equivalent to the dimension of parameter space.
Attention:
: Don't implement, if the model has no parameters. This will cause desirable compile time errors, if one tries to learn a model without parameters.
Referenced by PeakParameterFwhm< ParameterModel >::learn_().
virtual void setParameter (unsigned index, double value) [pure virtual]
0 <= index < this->numberOfParameters() .
Attention:
: Don't implement, if the model has no parameters. This will cause desirable compile time errors, if one tries to learn a model without parameters.
Exceptions:
psf::PreconditionViolation Parameter index is out of range or the number of parameters is zero.
Referenced by PeakParameterFwhm< ParameterModel >::learn_().
virtual GeneralizedSlope slopeInParameterSpaceFor (double x) const [protected, pure virtual]
The slope of the linear function representing the model in parameter space.
In parameter space the coordinates and regular parameters of the model are switching their roles. Some models may have a linear representation in this space: . is the generalized slope including the bias. In a n-dimensional parameter space, the generalized slope is (n+1)-dimensional. So, the parameter vector has n+1 elements with the last element always set to unity. Example: For the model with parameters a,b and c, the generalized slope in parameter space is and .
Attention:
This function is part of the optional interface, since not every model may have a linear representation in parameter space.
See also:
psf::PeakParameterModel::GeneralizedSlope
Parameters:
x The coordinate x now playing the role of a parameter.
Returns:
The generalized slope, a mulitdimensional vector including the bias.
Referenced by PeakParameterFwhm< ParameterModel >::learn_().
The documentation for this class was generated from the following file:
PeakParameter.h