psf: PeakParameterFwhm< ParameterModel > Class Template Reference
PeakParameterFwhm< ParameterModel > Class Template Reference
Public Member Functions
double at (const double mz) const
double getMinimalPeakHeightToLearnFrom ()
virtual double getParameter (unsigned index)
template<typename FwdIter , typename MzExtractor , typename IntensityExtractor >
void learnFrom (const MzExtractor &, const IntensityExtractor &, FwdIter first, FwdIter last)
virtual unsigned int numberOfParameters ()=0
void setMinimalPeakHeightToLearnFrom (double minimalHeight)
virtual void setParameter (unsigned index, double value)=0
Protected Member Functions
virtual GeneralizedSlope slopeInParameterSpaceFor (double x) const =0
Private Member Functions
template<typename MzExtractor >
void learn_ (const std::vector< std::pair< typename MzExtractor::result_type, typename MzExtractor::result_type > > &pairs)
Private Attributes
double minimalPeakHeightToLearnFrom_
Static Private Attributes
static const double fractionOfMaximum_
Detailed Description
template<typename ParameterModel>
class psf::PeakParameterFwhm< ParameterModel >
'Full width at half maximum' peak shape parameter.
The FWHM can be used to paramterize a peak shape.
Usually, the FWHM depends on the mass over charge ratio in a mass spectrum. This dependency can be linear, quadratic or any other function. Therefore, the PeakParameterFwhm is a template, which has to be instantiated with a concrete ParameterModel. Note, that the model should yield non-negative values for non-negative parameters and mz values (There is no such thing as a negative FWHM). Else, you will probably get very unexpected behaviour.
See also:
psf::ConstantModel, psf::LinearSqrtModel, psf::LinearSqrtOriginModel psf::SqrtModel, psf::QuadraticModel
psf::PeakShape
psf::GaussianPeakShape
Author:
Bernhard Kausler <bernhard.kausler@iwr.uni-heidelberg.de>
Definition at line 429 of file PeakParameter.h.
Member Function Documentation
double at (const double mz) const [virtual]
The FWHM at a specific mass channel.
Parameters:
mz Mass channel; has to be positive.
Exceptions:
psf::PreconditionViolation Parameter mz is not positive.
psf::PostconditionViolation The computed fwhm is negative or zero. This may be caused by an invalid ParameterModel.
Implements ParameterModel.
Definition at line 442 of file PeakParameter.h.
References ParameterModel::at().
Referenced by PeakParameterFwhm< ParameterModel >::learnFrom().
double getMinimalPeakHeightToLearnFrom ()
Only peaks with this absolute minimal intensity are used for learning.
Definition at line 576 of file PeakParameter.h.
Referenced by PeakParameterFwhm< ParameterModel >::learnFrom().
virtual double getParameter (unsigned index) [virtual, inherited]
0 <= index < this->numberOfParameters() .
Attention:
: Don't implement, if the model has no parameters. This will cause desirable compile time errors, if one tries to learn a model without parameters.
Exceptions:
psf::PreconditionViolation Parameter index is out of range or the number of parameters is zero.
void learn_ (const std::vector< std::pair< typename MzExtractor::result_type, typename MzExtractor::result_type > > & pairs) [private]
Fit the parameter model to measured mz-width pairs.
Internally, a linear regression using least squares is done. The PeakParameterModel has to support the optional slopeInParameterSpaceFor() function for this regression to work. Else, calling this function will not compile.
If new regression methods should be added, move the implementation of the learn_ function to policy classes.
Exceptions:
psf::PreconditionViolation Parameter pairs is an empty vector.
psf::InvariantViolation Numerical regression algorithm failed.
Definition at line 583 of file PeakParameter.h.
References ParameterModel::numberOfParameters(), ParameterModel::setParameter(), and ParameterModel::slopeInParameterSpaceFor().
void learnFrom (const MzExtractor & get_mz, const IntensityExtractor & get_int, FwdIter first, FwdIter last)
Calibrates the internal model for a specific mass spectrum.
Use this function to learn from a sequence of spectrum elements.
Note, that there is no internal error threshold or similar for the quality of the calibration. The calibration is performed as long as it is possible in any way. To achieve a good result, one should filter out the noise of the input spectrum and/ or use high quality data in the first place.
The distance (last - first) may not be negative, else the behaviour is undefined. It doesn't violate the preconditions, if (last - first) is zero or small. Nevertheless, it increases the chance of a Starvation exception to happen.
Parameters:
first Points to the first Element of the sequence.
last Points to one past the last Element of the sequence.
Exceptions:
psf::Starvation To few or bad data extracted from the input sequence to make a calibration possible.
Definition at line 547 of file PeakParameter.h.
References PeakParameterFwhm< ParameterModel >::at(), PeakParameterFwhm< ParameterModel >::getMinimalPeakHeightToLearnFrom(), and psf::measureFullWidths().
virtual unsigned int numberOfParameters () [pure virtual, inherited]
The number of parameters in the model.
May be any positive number including zero. This is equivalent to the dimension of parameter space.
Attention:
: Don't implement, if the model has no parameters. This will cause desirable compile time errors, if one tries to learn a model without parameters.
Referenced by PeakParameterFwhm< ParameterModel >::learn_().
void setMinimalPeakHeightToLearnFrom (double minimalHeight)
Only use peaks with a minimum absolute intensity to learn from.
Parameters:
minimalHeight May be negative, albeit that's not meaningful.
Definition at line 571 of file PeakParameter.h.
virtual void setParameter (unsigned index, double value) [pure virtual, inherited]
0 <= index < this->numberOfParameters() .
Attention:
: Don't implement, if the model has no parameters. This will cause desirable compile time errors, if one tries to learn a model without parameters.
Exceptions:
psf::PreconditionViolation Parameter index is out of range or the number of parameters is zero.
Referenced by PeakParameterFwhm< ParameterModel >::learn_().
virtual GeneralizedSlope slopeInParameterSpaceFor (double x) const [protected, pure virtual, inherited]
The slope of the linear function representing the model in parameter space.
In parameter space the coordinates and regular parameters of the model are switching their roles. Some models may have a linear representation in this space: . is the generalized slope including the bias. In a n-dimensional parameter space, the generalized slope is (n+1)-dimensional. So, the parameter vector has n+1 elements with the last element always set to unity. Example: For the model with parameters a,b and c, the generalized slope in parameter space is and .
Attention:
This function is part of the optional interface, since not every model may have a linear representation in parameter space.
See also:
psf::PeakParameterModel::GeneralizedSlope
Parameters:
x The coordinate x now playing the role of a parameter.
Returns:
The generalized slope, a mulitdimensional vector including the bias.
Referenced by PeakParameterFwhm< ParameterModel >::learn_().
The documentation for this class was generated from the following file:
PeakParameter.h