psf: LorentzianPeakShape Class Reference
LorentzianPeakShape Class Reference
Public Member Functions
LorentzianPeakShape (double fwhm=0.1, const double fwhmFactorForSupportThreshold=5.0)
double at (const double xCoordinate) const
double getFwhm () const
double getFwhmFactorForSupportThreshold () const
double getSupportThreshold () const
void setFwhm (double fwhm)
void setFwhmFactorForSupportThreshold (const double factor)
Private Attributes
double fwhm_
double fwhmFactorForSupportThreshold_
Friends
struct ::peakshapeTestSuite
Detailed Description
A lorentzian peak shape.
The Lorentzian is .
The Lorentzian is centered around zero.
See also:
psf::PeakShape
Author:
Bernhard Kausler <bernhard.kausler@iwr.uni-heidelberg.de>
Definition at line 277 of file PeakShape.h.
Member Function Documentation
double getFwhm () const
Gets the full width at half maximum.
Definition at line 29 of file LorentzianPeakShape.cpp.
Referenced by LorentzianPeakShape::getSupportThreshold().
double getFwhmFactorForSupportThreshold () const
Returns the factor used in the support threshold calculation.
Definition at line 37 of file LorentzianPeakShape.cpp.
Referenced by LorentzianPeakShape::getSupportThreshold().
double getSupportThreshold () const
The support threshold for the gaussian is calculated according to 'sigma x sigmaFactorForSupportThreshold'.
Definition at line 12 of file LorentzianPeakShape.cpp.
References LorentzianPeakShape::getFwhm(), and LorentzianPeakShape::getFwhmFactorForSupportThreshold().
void setFwhm (double fwhm)
Sets the full width at half maximum.
Parameters:
fwhm Has to be positive.
Exceptions:
psf::PreconditionViolation fwhm is not positive.
Definition at line 25 of file LorentzianPeakShape.cpp.
void setFwhmFactorForSupportThreshold (const double factor)
Sets the factor for the threshold calculation.
Parameters:
factor Has to be positive.
Exceptions:
psf::PreconditionViolation factor is not positive.
Definition at line 33 of file LorentzianPeakShape.cpp.
The documentation for this class was generated from the following files:
PeakShape.h
LorentzianPeakShape.cpp